# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# For option meanings, see rpm-ostreed.conf(5).

[Daemon]
# Habilita actualizaciones automáticas (o al menos la descarga) para que el demonio
# limpie las capas obsoletas por sí solo tras aplicar un rebase.
AutomaticUpdatePolicy=stage
# Fuerza al demonio a liberar memoria RAM cuando no está operando
IdleExitTimeout=60
#LockLayering=false
#Recommends=true
