name: Build Custom Fedora Atomic
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * 0'

env:
  IMAGE_NAME: fedora_atomic
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Image with Privileged Docker
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest -f Containerfile .

      - name: Push to GHCR
        run: |
          docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
